### ISSUE TITLE
Get Listed Request: [NanoMQ]

### ISSUE THREAD

**Issue by JaylinYu** [eclipse-sparkplug/sparkplug.listings#13]
### Organization Name and Organization URL

EMQ
https://www.emqx.com/en

### Product Name, Version, and Download/Product Information URL

NanoMQ v0.17.9
Product information: https://nanomq.io/
Download: https://nanomq.io/downloads?os=Linux or https://github.com/emqx/nanomq/releases/tag/0.17.9

### Product Logo URL

https://nanomq.io/images/logo.png

### Specification Version Used and download URL

Eclipse Sparkplug v3.0.0: http://www.eclipse.org/tahu/spec/sparkplug_spec.pdf
TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Compliant MQTT Server

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

Sparkplug TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
SHA-256: 90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f Eclipse-Sparkplug-TCK-3.0.0.zip

### Public URL of TCK Results Summary

https://nanomq.io/verification/summary.html

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

Dell XPS 13 9350
Ubuntu 22.04.2 LTS
NanoMQ 0.17.9 built by GCC 11

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by wes-johnson** [comment]
Reviewed and Approved.

**Comment by wes-johnson** [comment]
https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/167 has been created to get the listing done.

**Comment by wes-johnson** [comment]
This is now listed.
