### ISSUE TITLE
Get Listed Request: [Litmus Sparkplug Edge Node]

### ISSUE THREAD

**Issue by amine-amaach** [eclipse-sparkplug/sparkplug.listings#14]
### Organization Name and Organization URL

**Litmus Automation Inc.** : https://litmus.io/

### Product Name, Version, and Download/Product Information URL

LE Sparkplug Edge Node v1.3.1
Product Info: [https://central.litmus.io/solutions/le-sparkplug-edge-node/](https://central.litmus.io/listing/le-sparkplug-edge-node/)
Product Download: https://central.litmus.io/products/le-sparkplug-edge-node/

### Product Logo URL

https://central.litmus.io/wp-content/uploads/2022/10/Litmus_Logo.jpg

### Specification Version Used and download URL

Eclipse Sparkplug v3.0.0: http://www.eclipse.org/tahu/spec/sparkplug_spec.pdf
TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Edge Node

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

Sparkplug TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
SHA-256: 90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f Eclipse-Sparkplug-TCK-3.0.0.zip

### Public URL of TCK Results Summary

https://central.litmus.io/sparkplug-tck-results-summary/

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

- Dell Latitude 5430
- Microsoft Windows 10 Business
- [Litmus Edge](https://litmus.io/litmus-edge/) ([Download](https://central.litmus.io/products/litmus-edge-15day-trial/))

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by wes-johnson** [comment]
Reviewed and Approved.

**Comment by wes-johnson** [comment]
This has been created: https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/168

**Comment by wes-johnson** [comment]
This is now listed.
