### ISSUE TITLE
Get Listed Request: Opto 22 groov EPIC

### ISSUE THREAD

**Issue by bryce-nakatani** [eclipse-sparkplug/sparkplug.listings#16]
### Organization Name and Organization URL

Opto 22
https://www.opto22.com/
Logo: 
https://www.opto22.com/Opto22/media/opto22logos/Opto22_logo_gradient_wtagline_yeia.pdf

### Product Name, Version, and Download/Product Information URL

Product Name:	groov EPIC
Version:	Firmware 3.5.0-b.56
URL:	https://www.opto22.com/products/product-container/grv-epic-pr1;
URL: https://www.opto22.com/products/product-container/grv-epic-pr2
Firmware:	Available through manage.groov.com (account required).

### Product Logo URL

Product Logo URL:
https://www.opto22.com/Opto22/media/opto22logos/groov_EPIC_gradient_dark.pdf

### Specification Version Used and download URL

Version: 3.0.0
Specification: http://www.eclipse.org/tahu/spec/sparkplug_spec.pdf

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Edge Node

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

TCK: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
Fingerprint:  90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f

### Public URL of TCK Results Summary

https://downloads.opto22.com/EPIC-3.5.0-TCK-Results.html

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

Device
  groov EPIC (GRV-EPIC-PR1)
Software Components
  HiveMQ 2022.1
  Mosquitto 2.0.15
Operating Systems
  Ubuntu 22.04.2; LTS (TCK)
  Windows 11; 22H2

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by wes-johnson** [comment]
Reviewed and approved

**Comment by wes-johnson** [comment]
This has been created to wrap this up:
https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/170

**Comment by wes-johnson** [comment]
https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/170 has been closed and the listing is now live.
