### ISSUE TITLE
Get Listed Request: Opto 22 groov RIO & Sparkplug Specification 3.0.0

### ISSUE THREAD

**Issue by bryce-nakatani** [eclipse-sparkplug/sparkplug.listings#17]
### Organization Name and Organization URL

Opto 22
https://www.opto22.com/
Logo: 
https://www.opto22.com/Opto22/media/opto22logos/Opto22_logo_gradient_wtagline_yeia.pdf

### Product Name, Version, and Download/Product Information URL

Product Name:
Opto 22 groov RIO 
Version:
Firmware 3.5.0-b.46
URL:
(Part Number: GRV-R7-MM1001-10)
https://www.opto22.com/products/product-container/grv-r7-mm1001-10
(Part Number: GRV-R7-MM2001-10)
https://www.opto22.com/products/product-container/grv-r7-mm2001-10
(Part Number: GRV-R7-I1VAPM-3)
https://www.opto22.com/products/product-container/grv-r7-i1vapm-3 

Firmware:
(Part Number: GRV-R7-MM1001-10)
https://www.opto22.com/support/resources-tools/downloads/grv-r7-mm1001-10-firmware
(Part Number: GRV-R7-MM2001-10)
https://www.opto22.com/support/resources-tools/downloads/grv-r7-mm2001-10-firmware
(Part Number: GRV-R7-I1VAPM-3)
https://www.opto22.com/support/resources-tools/downloads/grv-r7-i1vapm-3-firmware

### Product Logo URL

https://www.opto22.com/Opto22/media/opto22logos/groov_RIO_solid_dark.pdf

### Specification Version Used and download URL

3.0.0
https://www.eclipse.org/tahu/spec/sparkplug_spec.pdf

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Edge Node

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f

### Public URL of TCK Results Summary

https://downloads.opto22.com/RIO-3.5.0-TCK-Results.html

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

Devices
  GRV-R7-MM1001-10
  GRV-R7-MM2001-10
  GRV-R7-I1VAPM-3)
Software Components
  HiveMQ 2022.1
  Mosquitto 2.0.15
Operating Systems
  Ubuntu 22.04.3 LTS
  Windows 11; 22H2

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by wes-johnson** [comment]
Reviewed and approved

**Comment by wes-johnson** [comment]
This has been created to get the listing done:
https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/171

**Comment by wes-johnson** [comment]
This is now complete and listed
