### ISSUE TITLE
Get Listed Request: Canary Publisher & Sparkplug Specification 3.0.0

### ISSUE THREAD

**Issue by joshwolf-canary** [eclipse-sparkplug/sparkplug.listings#19]
### Organization Name and Organization URL

Canary Labs, Inc.
https://www.canarylabs.com/

### Product Name, Version, and Download/Product Information URL

Product Name:
Canary Publisher
Version: 23.0.0
URL:
https://helpcenter.canarylabs.com/t/m1hvlty/publisher-overview-version-23

### Product Logo URL

https://www.canarylabs.com/images/CanaryLabs_Logo.svg

### Specification Version Used and download URL

3.0.0
https://www.eclipse.org/tahu/spec/sparkplug_spec.pdf

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Edge Node

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

3.0.0
https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f

### Public URL of TCK Results Summary

https://helpcenter.canarylabs.com/t/60yqgw8/publisher-sparkplugb-30-compliance-version-23

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

Virtual Machine
Windows Server 2022 Standard Version 10.0.20348
Canary Publisher Version 23.0.0.23220
HiveMQ Community Edition 2023.5
Eclipse Sparkplug TCK Extension 3.0.0

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by wes-johnson** [comment]
Reviewed and approved. This has been created to complete the listing: https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/174
