### ISSUE TITLE
Get Listed Request: HiveMQ MQTT Broker

### ISSUE THREAD

**Issue by ahelmbr** [eclipse-sparkplug/sparkplug.listings#2]
### Organization Name and Organization URL

HiveMQ GmbH
https://www.hivemq.com/

### Product Name, Version, and Download/Product Information URL

HiveMQ MQTT Broker Version 4.x Community and Professional Editions

https://www.hivemq.com/releases/hivemq-4.9.1.zip
https://github.com/hivemq/hivemq-community-edition/releases/download/2022.1/hivemq-ce-2022.1.zip

### Product Logo URL

https://www.hivemq.com/logos-and-media-kit/

### Specification Version Used and download URL

Sparkplug Version 3.0.0 
org.eclipse.tahu:tahu-core:1.0.0
https://repo1.maven.org/maven2/org/eclipse/tahu/tahu-core/1.0.0/

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Aware MQTT Server

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

TCK v 3.0.0-rc1.  d1cd704
https://github.com/eclipse-sparkplug/sparkplug/releases/tag/v3.0.0-rc1

https://github.com/eclipse-sparkplug/sparkplug/archive/refs/tags/v3.0.0-rc1.tar.gz

### Public URL of TCK Results Summary

https://www.hivemq.com/verification/summary.html

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

Apple M1 Pro , 32 GB,
MacOS ventura 13.0

Sparkplug Compliant MQTT Server:  No further Sparkplug Devices are needed to get certifoed
Sparkplug Aware MQTT Server:  Edge & Device simulation with HiveMQ Swarm MQTT Simulator + Sparkplug B Payload Generator

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by ahelmbr** [comment]
I think this Issue is not implemented as expected. Currently  only  the HiveMQ Sparkplug Aware Extension is listed as compatible product.(see at https://sparkplug.eclipse.org/compatibility/compatible-software/)  This makes finally no sense. The HiveMQ Broker is the Sparkplug compatible  Broker and in combination with the HiveMQ Sparkplug Aware Extension it is also a Sparkplug Aware Broker.

**Comment by ahelmbr** [comment]
I think this request is not yet  implemented as expected. Currently  only  the HiveMQ Sparkplug Aware Extension is listed as compatible product.(see at https://sparkplug.eclipse.org/compatibility/compatible-software/)  This makes finally no sense. The HiveMQ Broker is the Sparkplug compatible  Broker and in combination with the HiveMQ Sparkplug Aware Extension it is also a Sparkplug Aware Broker.

**Comment by fdesbiens** [comment]
Hi @ahelmbr.

The HiveMQ Sparkplug-aware extension is one of the two components used to ratify Sparkplug v3.0. The other one is Eclipse Tahu. This is why both are listed as compatible products as of now. 

Of course, the extension on its own is only useful with a broker. This is why you need to submit this request to submit the HiveMQ broker as compatible. 

I notice your issue mentions RC1 of the TCK. "Get Listed" requests need to rely on official TCK releases only. Please make sure the products submitted pass the ratified TCK for Sparkplug v3.0.0 found here:

https://projects.eclipse.org/projects/iot.sparkplug/downloads

I would recommend closing this issue and opening a new one; make sure you specify the TCK Version Used, digital SHA-256 Fingerprint, and Download URL for the TCK used for validation in your request. 

Thank you for your understanding and Happy New Year!

**Comment by ahelmbr** [comment]
Created a New one - to remove confusion about sparkplug extension and Broker.
