### ISSUE TITLE
Get Listed Request: Smart IOT Highway v2.3.1

### ISSUE THREAD

**Issue by IntegrationObjects** [eclipse-sparkplug/sparkplug.listings#21]
### Organization Name and Organization URL

Integration Objects
https://integrationobjects.com/

### Product Name, Version, and Download/Product Information URL

Smart IOT Highway v 2.3.1
SIOTH MQTT Universal Broker v 2.3.1
SIOTH Master Broker v 2.3.1
product info : 
- https://integrationobjects.com/sioth/
- https://integrationobjects.com/sioth-opc/industrial-mqtt/mqtt-universal-broker/

### Product Logo URL

https://integrationobjects.com/images/2023/04/logo.webp

### Specification Version Used and download URL

Eclipse Sparkplug v3.0.0: http://www.eclipse.org/tahu/spec/sparkplug_spec.pdf
TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Aware MQTT Server

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

Sparkplug TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
SHA-256: 90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f Eclipse-Sparkplug-TCK-3.0.0.zip

### Public URL of TCK Results Summary

https://[integrationobjects.com/MQTT-Broker/summary.html](https://integrationobjects.com/MQTT-Broker/summary.html)

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

Dell OptiPlex 7050
OS  : Windows 10 Enterprise 22H2

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by fdesbiens** [comment]
@wes-johnson Integration Objects is a new member. Can you or another committer have a look at this request, please?

**Comment by bryce-nakatani** [comment]
Reviewed and Approved.

**Comment by bryce-nakatani** [comment]
@IntegrationObjects I'm creating the request to post your products to the Sparkplug Compatible Software page. Your request lists three products but only two web links. The tile will only point to a single link. Would you please clarify which web link associates to which product? Thank you.

**Comment by IntegrationObjects** [comment]
Hi you can use this link: https://integrationobjects.com/sioth/ 

 

Best,

**Comment by bryce-nakatani** [comment]
Hello @IntegrationObjects. Please take a look at https://preview-161--sparkplug-eclipse-org.eclipsecontent.org/compatibility/compatible-software/. Is this okay?

**Comment by IntegrationObjects** [comment]
Yes it does look good.

 


Can you please add “SIOTH®” in front of “Smart IoT Highway”? and ‘®’ whenever you write “SIOTH”


 


Thank you!

**Comment by bryce-nakatani** [comment]
Completed https://sparkplug.eclipse.org/compatibility/compatible-software/.
