### ISSUE TITLE
Get Listed Request: [Opto 22 groov EPIC Firmware 3.6.0]

### ISSUE THREAD

**Issue by bryce-nakatani** [eclipse-sparkplug/sparkplug.listings#22]
### Organization Name and Organization URL

Opto 22
https://www.opto22.com/
Logo
https://www.opto22.com/Opto22/media/opto22logos/Opto22_logo_gradient_wtagline_yeia.pdf

### Product Name, Version, and Download/Product Information URL

Product Name:
  Opto 22 groov EPIC
Version:
  Firmware 3.6.0-b.32
URL:
  https://www.opto22.com/products/product-container/grv-epic-pr1;
  https://www.opto22.com/products/product-container/grv-epic-pr2
Firmware:
  Available through manage.groov.com (account required).

### Product Logo URL

https://www.opto22.com/Opto22/media/opto22logos/groov_EPIC_gradient_dark.pdf

### Specification Version Used and download URL

3.0.0
https://www.eclipse.org/tahu/spec/sparkplug_spec.pdf

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Edge Node

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

3.0.0
https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f

### Public URL of TCK Results Summary

https://downloads.opto22.com/EPIC-3.6.0-TCK-Results.html

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

Devices
  GRV-EPIC-PR1
  GRV-EPIC-PR2
Software Components
  HiveMQ 2022.1
  Mosquitto 2.0.18
Operating Systems
  Ubuntu 22.04.4; LTS
  Windows 11; 23H2

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by wes-johnson** [comment]
Reviewed and Approved.

**Comment by wes-johnson** [comment]
This has been created to wrap this up:
https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/176

**Comment by bryce-nakatani** [comment]
Hello Wes,

I think this update is hung pending an approval from you. I placed a reply
but I wasn't the requester.

I'm okay with what's proposed by the webteam.

The changes (adding version information) we discussed is something that
could be covered later.

Bryce
