### ISSUE TITLE
Get Listed Request: N3uron SparkPipe v0.0.5

### ISSUE THREAD

**Issue by daniel-paesa** [eclipse-sparkplug/sparkplug.listings#24]
### Organization Name and Organization URL

N3uron Connectivity Systems: https://n3uron.com/

### Product Name, Version, and Download/Product Information URL

SparkPipe v0.0.5
https://docs.n3uron.com/docs/sparkpipe-introduction
https://aws.amazon.com/marketplace/pp/prodview-xiiaocgyyc3z2

### Product Logo URL

https://dl.n3uron.com/sparkpipe-logo.png

### Specification Version Used and download URL

Eclipse Sparkplug v3.0.0: https://www.eclipse.org/tahu/spec/sparkplug_spec.pdf
TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Host Application

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

Sparkplug TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
SHA-256: A70B2C2F00D67AC714EADD5AC50F6241E0EFA26036D95CA8EC667D491021B86B

### Public URL of TCK Results Summary

https://dl.n3uron.com/SparkplugTCKResults.log

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

SparkPipe v0.0.5 (AWS EC2)
HiveMQ Community Edition 2024.6

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by bryce-nakatani** [comment]
I post processed your results with the TCK's Python postprocessor (attached).  The results from the SendCommand test are incomplete. Specifically it looks like NCMD and DCMD messages were not evaluated.
[summary.zip](https://github.com/user-attachments/files/16268057/summary.zip)

**Comment by daniel-paesa** [comment]
I had issues using the Python script to generate the HTML report, so I uploaded the raw logs.

Regarding the SendCommand test, we are unable to properly evaluate this test as our software acts as a host application but does not support writing to arbitrary metrics, it acts as a bridge between the MQTT broker with Sparkplug traffic and publishes the metrics it receives to Kafka. 

Sending commands is implemented and it requests rebirths if necessary (out-of-order timeout, etc..) but is not interactive and cannot be requested by the user on-demand.

**Comment by bryce-nakatani** [comment]
The logs are not an issue. I processed them to make the appearance of the results more consistent. In the 3.0.0 TCK, if you copied the TCK's "src" directory tree to the same directory as the python script, the postprocessor will work.

The implementation makes sense and thank you for the explanation. Would your application issue a "Node Control/Rebirth" NCMD to an unknown or an offline edge node?

**Comment by daniel-paesa** [comment]
It issues a "Node Control/Rebirth" command in the following cases:

- Receives data from an unknown (never received a birth) node
- Receives an unknown metric not specified in the previous birth
- Receives a metric with an unknown alias
- Receives more than one metric from the same node using the same alias (duplicate)
- Receives a device birth without a previous node birth
- Receives device metrics without a previous device birth
- Receives out-of-order messages and the configured timeout (defaults to 5s) has passed.
- Receives a metric after a node or device death

**Comment by bryce-nakatani** [comment]
Your Get-Listed request has been reviewed and approved for a listening only host application.

**Comment by bryce-nakatani** [comment]
Please review the preview at https://preview-163--sparkplug-eclipse-org.eclipsecontent.org/compatibility/compatible-software/. Is this acceptable?

**Comment by daniel-paesa** [comment]
We have updated the logo for **SparkPipe**, you can find it at https://dl.n3uron.com/n3-sparkpipe-logo.jpg

Can you please update the webpage with the new logo?

**Comment by bryce-nakatani** [comment]
There is a new requirement that I was unaware of. Would you please convert the image to PNG or SVG format and reply with a link to it.

**Comment by daniel-paesa** [comment]
Sure, you can find it here --> https://dl.n3uron.com/n3-sparkpipe-logotype_v2.png

**Comment by bryce-nakatani** [comment]
Thank you. The preview has been updated. Please review https://preview-163--sparkplug-eclipse-org.eclipsecontent.org/compatibility/compatible-software/. Is this acceptable?

**Comment by daniel-paesa** [comment]
Looks good to me, go ahead.

Thanks

**Comment by bryce-nakatani** [comment]
Completed. See https://sparkplug.eclipse.org/compatibility/compatible-software/
