### ISSUE TITLE
Get Listed Request: HiveMQ Broker

### ISSUE THREAD

**Issue by ahelmbr** [eclipse-sparkplug/sparkplug.listings#3]
### Organization Name and Organization URL

HiveMQ GmbH
https://www.hivemq.com/

### Product Name, Version, and Download/Product Information URL

HiveMQ MQTT Broker Version 4.x Community and Professional Editions

https://www.hivemq.com/releases/hivemq-4.9.1.zip
https://github.com/hivemq/hivemq-community-edition/releases/download/2022.1/hivemq-ce-2022.1.zip

### Product Logo URL

https://www.hivemq.com/logos-and-media-kit/

### Specification Version Used and download URL

Sparkplug Version 3.0.0
org.eclipse.tahu:tahu-core:1.0.0
https://repo1.maven.org/maven2/org/eclipse/tahu/tahu-core/1.0.0/

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Compliant MQTT Server

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

Sparkplug TCK v3.0.0
https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f  Eclipse-Sparkplug-TCK-3.0.0.zip

### Public URL of TCK Results Summary

https://www.hivemq.com/verification/summary.html 

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

Apple M1 Pro , 32 GB,
MacOS ventura 13.1

Sparkplug Compliant MQTT Server: No further Sparkplug Devices are needed to get certifoed
Sparkplug Aware MQTT Server: Edge & Device simulation with HiveMQ Swarm MQTT Simulator + Sparkplug B Payload Generator

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by wes-johnson** [comment]
Reviewed and Approved.

**Comment by fdesbiens** [comment]
Thanks for opening this issue @ahelmbr.

 I created an issue on the Sparkplug website repository to get your product added to the list of compatible products. You will find it here: https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/158

**Comment by fdesbiens** [comment]
The webmasters implemented the change. You can close the issue, @wes-johnson.
