### ISSUE TITLE
Get Listed Request: N3uron Client for Sparkplug v1.2.0

### ISSUE THREAD

**Issue by Llorx** [eclipse-sparkplug/sparkplug.listings#7]
### Organization Name and Organization URL

N3uron Connectivity Systems: https://n3uron.com/

### Product Name, Version, and Download/Product Information URL

Client for Sparkplug v1.2.0: https://n3uron.com/iiot-platform-modules/sparkplug-client/

### Product Logo URL

https://n3uron.com/wp-content/uploads/2020/02/n3uron-company-logotype-orange.svg

### Specification Version Used and download URL

Eclipse Sparkplug v3.0.0: http://www.eclipse.org/tahu/spec/sparkplug_spec.pdf
TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Edge Node

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

Sparkplug TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
SHA-256: 90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f Eclipse-Sparkplug-TCK-3.0.0.zip

### Public URL of TCK Results Summary

https://n3uron.com/wp-content/uploads/2023/01/n3clientforsparkplugv1.2.0compliance.html

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

- MSI Creator Pro
- Windows 10 Pro 22H2
- N3uron V.1.21: https://n3uron.com/downloads-software/

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by wes-johnson** [comment]
Reviewed and Approved.

**Comment by fdesbiens** [comment]
Thanks for opening this issue @Llorx.

I created an issue on the Sparkplug website repository to get your product added to the list of compatible products. You will find it here: https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/162

**Comment by Llorx** [comment]
Perfect. Thank you both @wes-johnson and @fdesbiens 😊
