### ISSUE TITLE
Get Listed Request: Ignition by Inductive Automation v8.1.23

### ISSUE THREAD

**Issue by iatraviscox** [eclipse-sparkplug/sparkplug.listings#8]
### Organization Name and Organization URL

Inductive Automation
[http://inductiveautomation.com/](http://inductiveautomation.com/)

Submitted with Cirrus Link Solutions (joint listing)

### Product Name, Version, and Download/Product Information URL

Ignition by Inductive Automation v8.1.23
MQTT Transmission Module v4.0.14
MQTT Engine Module v4.0.14
MQTT Distributor Module v4.0.14
Product Info: [https://inductiveautomation.com/ignition/](https://inductiveautomation.com/ignition/)
Product Download: [https://inductiveautomation.com/downloads/](https://inductiveautomation.com/downloads/)

### Product Logo URL

[Logo_Ignition_(R).eps](https://company-36882.frontify.com/api/attachment/download/eyJibG9ja19yZWZlcmVuY2UiOm51bGwsImlkIjoiMjk5MDUwIn0:frontify:mRG3PbxfWRxoyHcAJOTj7nujQ4gAwUDYtl0uNm5kP_U)
[All Brand Resources](https://company-36882.frontify.com/d/PvUNchzTCkyj/inductive-automation-brand-guidelines)

### Specification Version Used and download URL

Eclipse Sparkplug v3.0.0: [http://www.eclipse.org/tahu/spec/sparkplug_spec.pdf](http://www.eclipse.org/tahu/spec/sparkplug_spec.pdf)
TCK v3.0.0: [https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip](https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip)

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Host Application

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

Sparkplug TCK v3.0.0: [https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip](https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip)
SHA-256: 90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f Eclipse-Sparkplug-TCK-3.0.0.zip

### Public URL of TCK Results Summary

MQTT Transmission Module: [https://docs.chariot.io/display/CLD80/MQTT+Transmission+v4.0.14+Compliance](https://docs.chariot.io/display/CLD80/MQTT+Transmission+v4.0.14+Compliance)
MQTT Engine Module: [https://docs.chariot.io/display/CLD80/MQTT+Engine+v4.0.14+Compliance](https://docs.chariot.io/display/CLD80/MQTT+Engine+v4.0.14+Compliance)
MQTT Distributor Module: [https://docs.chariot.io/display/CLD80/MQTT+Distributor+v4.0.14+Compliance](https://docs.chariot.io/display/CLD80/MQTT+Distributor+v4.0.14+Compliance)

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

Macbook Pro
Mac OS 13.0.1 (22A400)
Ignition v8.1.23: [https://inductiveautomation.com/downloads/ignition/8.1.23](https://inductiveautomation.com/downloads/ignition/8.1.23)

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by bryce-nakatani** [comment]
Reviewed and Approved.

**Comment by fdesbiens** [comment]
Thanks for opening this issue @iatraviscox .

I created an issue on the Sparkplug website repository to add your product to the compatible products list. You will find it here: https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/163
