### ISSUE TITLE
Get Listed Request: SignalFire Ranger v0.1.27

### ISSUE THREAD

**Issue by rpiper** [eclipse-sparkplug/sparkplug.listings#9]
### Organization Name and Organization URL

SignalFire Telemetry: https://www.signal-fire.com/

### Product Name, Version, and Download/Product Information URL

SignalFire Ranger v0.1.27: https://www.signal-fire.com/lte-m1-cellular-products/ranger-node/

### Product Logo URL

https://www.signal-fire.com/wp-content/uploads/2021/04/RANGER-Web-Logo-TMed-FINAL.jpg

### Specification Version Used and download URL

Eclipse Sparkplug v3.0.0: http://www.eclipse.org/tahu/spec/sparkplug_spec.pdf

### Sparkplug Conformance Profile(s) covered by this product

Sparkplug Edge Node

### TCK Version Used, digital SHA-256 Fingerprint, and Download URL

Sparkplug TCK v3.0.0: https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip
SHA256 hash of Eclipse-Sparkplug-TCK-3.0.0.zip: 90e018a9d460ba8fd9c57dd9a38615b9c0f953881f164588f1b1120151408d8f

### Public URL of TCK Results Summary

https://www.signal-fire.com/summary.html

### Summary of the Environment Used for Certification - Devices, Software Components, Operating Systems, Cloud Services, etc

•	Ubuntu 22.10 (GNU/Linux 5.19.0-29-generic x86_64)
•	HiveMQ Community Edition 2022.1
•	SignalFire Ranger, A2D1 Expansion Card, HW Rev 2.1, FW v0.1.27

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

### All TCK Requirements are met

- [X] I attest that all TCK requirements have been met

**Comment by wes-johnson** [comment]
Reviewed and Approved.

**Comment by fdesbiens** [comment]
Thanks for opening this issue @rpiper.

I created an issue on the Sparkplug website repository to add your product to the compatible products list. You will find it here: https://gitlab.eclipse.org/eclipsefdn/it/websites/sparkplug.eclipse.org/-/issues/164

**Comment by fdesbiens** [comment]
@rpiper Our webmasters implemented the tile for your product. However, the logo you submitted does not have a transparent background. Would you like for us to proceed with it, or would you prefer to replace it with a transparent PNG or SVG?  Please note we cannot modify logos provided by submitters ourselves.

You can see a preview here: https://preview-146--sparkplug-eclipse-org.eclipsecontent.org/compatibility/compatible-software/ Let me know your decision by replying to this issue.

**Comment by rpiper** [comment]
@fdesbiens Thank you for sending the preview. Below is the link to a better image with a transparent background that we would prefer to use: https://www.signal-fire.com/wp-content/uploads/2023/02/Ranger-Logo-Transparent.png

Also, since the SignalFire Ranger is an Edge Node hardware device, shouldn't it be listed under the "SPARKPLUG COMPATIBLE HARDWARE" section, instead of the software section?

**Comment by fdesbiens** [comment]
Thank you for the image, @rpiper. 

I somehow missed that the Ranger is a device. I will ask the webmasters to add it to the correct tab. Thank you for pointing it out!
